# Generated by Django 5.1.5 on 2025-02-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="заголовок")),
                (
                    "content",
                    models.TextField(max_length=1500, verbose_name="содержимое"),
                ),
                (
                    "img",
                    models.ImageField(
                        default="404 error",
                        upload_to="media/img/",
                        verbose_name="изображение",
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["name"],
            },
        ),
    ]
