# Generated by Django 5.1.5 on 2025-02-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spam",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
