# Generated by Django 5.1.5 on 2025-02-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0002_alter_spam_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spam",
            name="img",
            field=models.ImageField(
                blank=True,
                default="static/404error.jpg",
                null=True,
                upload_to="media/img/",
                verbose_name="изображение",
            ),
        ),
    ]
