# Generated by Django 5.1.5 on 2025-02-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spam", "0003_alter_spam_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spam",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/img/",
                verbose_name="изображение",
            ),
        ),
    ]
