# Generated by Django 5.1.5 on 2025-02-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="описание"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="наименование")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="наименование")),
                (
                    "descriptions",
                    models.TextField(max_length=500, verbose_name="описание"),
                ),
                (
                    "img",
                    models.ImageField(upload_to="images/", verbose_name="изображение"),
                ),
                (
                    "category",
                    models.CharField(max_length=150, verbose_name="категория"),
                ),
                ("price", models.IntegerField(max_length=15, verbose_name="цена")),
                (
                    "created_at",
                    models.DateField(max_length=10, verbose_name="дата создания"),
                ),
                (
                    "updated_at",
                    models.DateField(
                        max_length=10, verbose_name="дата последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name"],
            },
        ),
    ]
