# Generated by Django 5.1.5 on 2025-02-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_category_alter_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                default="404 error", upload_to="media/img/", verbose_name="изображение"
            ),
        ),
    ]
