# Generated by Django 5.1.5 on 2025-03-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="наименование"
            ),
        ),
    ]
