# Generated by Django 5.1.5 on 2025-03-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auth",
            options={
                "ordering": ["email"],
                "permissions": [("can_publish_product", "Can publish new product")],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
