# Generated by Django 5.1.5 on 2025-03-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0005_alter_auth_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auth",
            options={
                "ordering": ["email"],
                "permissions": [
                    ("can_unpublish_product", "can unpublish new product"),
                    ("can_delete_product", "can delete product"),
                    ("can_edit_product", "can edit product"),
                    ("can_add_product", "can add product"),
                ],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
