# Generated by Django 5.1.5 on 2025-03-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0006_alter_auth_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auth",
            options={
                "ordering": ["email"],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
