# Generated by Django 5.1.5 on 2025-03-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0007_alter_auth_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auth",
            options={
                "ordering": ["email"],
                "permissions": [
                    ("can_add_product", "can add new product"),
                    ("can_view_product", "can view product"),
                ],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
